# Generated by Django 5.2.7 on 2025-10-17 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Memes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('meme', models.FileField(upload_to='memes/videos/')),
                ('tags', models.CharField(max_length=350)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memes', to='admin_app.category')),
            ],
        ),
    ]
